version: "3"

services:
  routr:
    image: fonoster/routr-one:latest
    environment:
      LOGS_LEVEL: verbose
      EXTERNAL_ADDRS: ${DOCKER_HOST_ADDRESS}
      CONNECT_VERIFIER_PUBLIC_KEY_PATH: /keys/public.key
    ports:
      - 51908:51908
      - 5062:5062
      - 5063:5063
    volumes:
      - ./.keys:/keys
      - shared:/var/lib/postgresql/data

volumes:
  shared: