version: "3"

services:

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC
      PGTZ: UTC
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
