name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out our bug report form."

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen instead of the bug.
      placeholder: Explain what you expected to happen after following the steps above.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, like links to related issues, screenshots, etc.
      placeholder: Provide more context here.
    validations:
      required: false
